name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Amazon ECR with AWS credentials and region
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2  # Set your region here (e.g., us-east-2, us-west-2, etc.)

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t public.ecr.aws/s5y7m4v1/tasky/a:latest .

    # Step 5: Push the Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker push public.ecr.aws/s5y7m4v1/tasky/a:latest
