name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Configure AWS Credentials using OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::495599743940:role/GitHubActionsEKSRole
        aws-region: us-east-1  # Must be us-east-1 for ECR Public

    # Step 4: Login to Amazon ECR Public
    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t public.ecr.aws/s5y7m4v1/tasky/a:${{ github.sha }} -t public.ecr.aws/s5y7m4v1/tasky/a:latest .

    # Step 6: Push the Docker image to ECR Public
    - name: Push Docker image to ECR Public
      run: |
        docker push public.ecr.aws/s5y7m4v1/tasky/a:${{ github.sha }}
        docker push public.ecr.aws/s5y7m4v1/tasky/a:latest
